// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnhossbwiyalpffxkspg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuaG9zc2J3aXlhbHBmZnhrc3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTE1MzEsImV4cCI6MjA3NDU2NzUzMX0.4zD6AAMS9uhG_FD1vJWtAYTZ_HdFJ6dbTK6TQfRG81I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});